### PR TITLE
Fixed matmul

### PR DESCRIPTION
**Pull request by mfalt**
See https://github.com/JuliaMath/DoubleFloats.jl/issues/45

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
Thanks for PR, good to have your help.

**Comment by mfalt** [comment]
Is there a reason for implementing `*` instead of `mul!` ?
`mul!` would alllow multiplication into pre-allocated matrices, and `*` falls back on pre-allocating anyway.
The only reason I can see is that the currecnt allocation is done through
```julia
result = reshape(Array{DoubleFloat{T}, 1}(undef, result_rows*result_cols), (result_rows, result_cols))
```
but I see no reason why it could not be allocated through the default
`Array{T,N}(undef, dims)`.

I'll try to rewrite the code to using `mul!` unless there is a good reason not to.

**Comment by JeffreySarnoff** [comment]
There is good reason to support matrix multiplication where `eltype(lhs) == eltype(rhs) == DoubleFloat{IEEEFloat}` as an infix operator.  This in no way precludes the utility of overloading `LinearAlgebra.mul!`.  DoubleFloats are intended to be available to and purpose suitable for work that does not involve `using GenericLinearAlgebra, LinearAlgebra`  yet may multiply two 1x1, 2x2, 3x3 Arrays with eltype as above.  Not all multiplication of, say square, arrays is in pursuit of technical aspects of LinearAlgebra.  DoubleFloats also serve to check and, with some quantifiable likelihood (or, at least, with a fuzzily characterizable tendency) to reassure the appropriateness of values obtained using, say, Float64s run through identical Julia functions or applied to from a given package.

So, please do provide the code to support mul! and please refrain from unwriting the current code. I do think it serves clarity and future work to separate the two semantic intents into their own files where doing so does not produce more tangles than it resolves.  _Let Me Know Your Thoughts_

**Comment by mfalt** [comment]
Thanks for taking the time to discuss this @JeffreySarnoff 
I am not sure that I understand what you are trying to say. I decided to do a pull request with something concrete to make it easier to discuss.

**Pull request merged**
