### PR TITLE
fix subnormal `sqrt` and `cbrt`

### PR DESCRIPTION
**Pull request by t-bltg**
Fix https://github.com/JuliaMath/DoubleFloats.jl/issues/166 (tests added).

Also remove `.DS_Store` files and add them to `.gitignore`.

- [x] benchmark performance

**PR**
```julia
julia> using BenchmarkTools, DoubleFloats
julia> x = Double64(1e-10);
julia> @btime sqrt($x)
  230.792 ns (0 allocations: 0 bytes)
```

**master**
```julia
julia> using BenchmarkTools, DoubleFloats
julia> x = Double64(1e-10)
julia> @btime sqrt($x)
  215.868 ns (0 allocations: 0 bytes)
```

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
for sqrt using 
```
HI(x) < 5.562684646268013e-309 && return DoubleFloat{T}(sqrt(HI(x)), zero(T))
```
for cbrt using
```
HI(x) < 7.458340731200208e-155 && return DoubleFloat{T}(cbrt(HI(x)), zero(T))
```
will be faster (and shrinks the special case space).

**Comment by JeffreySarnoff** [comment]
By hand. For example, at the end of the cbrt search
```

julia> x=prevfloat(y,3_545_284); cbrt(Double64(x))
NaN

julia> x=prevfloat(y,3_545_283); cbrt(Double64(x))
4.209340649576657e-52

julia> x
7.458340731200208e-155
```

**Comment by t-bltg** [comment]
I see, thanks.
Are we sure that we want to hardcode these numbers in the algorithm itself ?

Especially since these numbers are determined from the output of algorithm itself, any change to the aforementioned algorithm is likely to change these values and thus breaking the code again: I find it error prone and brittle.

**Comment by JeffreySarnoff** [comment]
For the algorithm as designed, they are the precise values -- changing the
design (esp for cbrt) would change that, but they are empirical.  The
alternative would be to check the result for NaN and then apply the
approximation.  That would be more general at the cost of slowdown
(checking all inputs for small inputs and checking results for small inputs
to see if they are NaN).

**Comment by t-bltg** [comment]
I've pushed an alternative in https://github.com/JuliaMath/DoubleFloats.jl/pull/167/commits/5b9941839337f5c98de0c561670fb3f2aa8f7cae, although I must admit that I find it less readable.

**Comment by t-bltg** [comment]
> By hand. For example, at the end of the cbrt search

What is `y` in your example ?

**Comment by JeffreySarnoff** [comment]
y is an approximation to the final value x,   3.351952e153 was found by informed search.
```
julia> yy = (floatmin(Float64) * 3.351952e153)
7.458340770170931e-155

julia> xx=prevfloat(yy, 3_545_283); cbrt(Double64(xx))
4.209340655803547e-52
```

**Pull request merged**
