### PR TITLE
tests with complex numbers

### PR DESCRIPTION
**Pull request by yikait2**

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
use `ComplexD64` and `==` (and it works -- but these are good to add to the tests, so make the changes and I will merge):
```
    # Complex multiplications with Double64 and Float64
    C1 = [1.0+2*im 3 4*im; 5 6 7-im]
    C2 = [im; 0; 5-7*im]
    C1C2 = C1*C2
    DC1DC2 = ComplexD64.(C1) * ComplexD64.(C2)
    DC1FC2 = ComplexD64.(C1) * C2
    FC1DC2 = C1 * ComplexD64.(C2)

    @test DC1DC2 == ComplexD64.(C1C2)
    @test DC1FC2 == ComplexD64.(C1C2)
    @test FC1DC2 == ComplexD64.(C1C2)
```

**Comment by JeffreySarnoff** [comment]
I added your tests by hand with `# Test with complex (thanks yikait2)`

**Comment by yikait2** [comment]
Would you please reopen it?

**Comment by JeffreySarnoff** [comment]
sure

**Comment by JeffreySarnoff** [comment]
Do you want me to remove the hand added version of your corrected PR?

**Comment by yikait2** [comment]
Sure, thanks!

**Comment by yikait2** [comment]
Sure! Thanks a lot!

**Pull request merged**
