### PR TITLE
WIP: clean up handling of zeros and infinities

### PR DESCRIPTION
**Pull request by RalphAS**
This PR starts by identifying some issues with zeros and infinities by means of broken tests.

The intention is to address (at least some of) these in subsequent commits.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
Why did you choose to replace
    ay, ax = minmax(ax, ay)
with
    if ax < ay
        ax, ay = ay, ax
    end

**Comment by JeffreySarnoff** [comment]
About the HILO representation of NaN and (signed) Inf:
I had forced the LO part to be NaN when the HI part is NaN +Inf -Inf after some investigation.
Often enough, Infs and NaNs are/should be handled out of line as an infrequent special case.
Doing so allows the finite values to be processed without additional delay (beyond `isnan(LO(x))`).
Making the LO part of NaN and signed Inf be 0.0 is less discriminating because there are valid finite values in addition to zero that have their LO part equal to 0.0 (e.g. 1.0).

Do you have a compelling reason to rework this?

**Comment by RalphAS** [comment]
WRT the 0 low-word for infinities, my goal was consistency.  It preserves the design concept that DoubleFloats are "unevaluated sums of two IEEE f.p. numbers".   I was trying to tweak things so that infinite values "just work". Having the `NaN` low-word caused several operations with infinities to return `NaN` instead of something consistent with IEEE-754.

Low-word `NaN` might be generated in intermediate computations of infinite values, but zeroing-by-canonicalization seems to prevent most subsequent problems.

In this package the existing checks all seem to be `isnan(HI(x))`. Did I miss something, or can I ask you to demonstrate more explicitly where testing for low-word `NaN` instead is helpful?

**Comment by JeffreySarnoff** [comment]
Ralph,
I am grateful for your interest and contributions.  As you have given this some of your time, let me provide a little more context.  I don't know what you know -- much background is covered in https://github.com/JuliaMath/DoubleFloats.jl/issues/11 (likely at a level you have passed, nevertheless, there should be some useful details therein).  

The files src\math\ops\op_dbdb_db.jl src\math\ops\op_dbfp_db.jl src\math\ops\op_fpdb_db.jl should use `!isnan(LO(_))` and instead have been using `!isnan(HI(_))`.  You have caught a bug. (thanks).

DoubleFloats are stored as two nonoverlapping floats and the arithmetic algorithms utilize this.  That is somewhat different from their cleanest conceptualization (in my opinion).  They are not IEEE 754 compliant as a numerical value.  They are floating point values with a significand that has variable precision (at least 106 bits (including hidden bits), at most ..more.. where the intervening bits between the two stored values are all zeros). And an exponent that has fixed precision (matching e.g. the exponent range of a Float64).

The delay in my response was unavoidable.

Jeffrey

**Comment by JeffreySarnoff** [comment]
Ralph,
I am grateful for your interest and contributions. As you have given this some of your time, let me provide a little more context. I don't know what you know -- much background is covered in #11 (likely at a level you have passed, nevertheless, there should be some useful details therein).

Actually -- I need to trace this all down.   The files src\math\ops\op_dbdb_db.jl src\math\ops\op_dbfp_db.jl src\math\ops\op_fpdb_db.jl and the routines they call are the ones in question. They do use !isnan(LO(_)) and maybe should have been using !isnan(HI(_)). if so, You have caught a bug (and thanks). Actually -- I need to trace this all down.  

DoubleFloats are stored as two nonoverlapping floats and the arithmetic algorithms utilize this. That is somewhat different from their cleanest conceptualization (in my opinion). They are not IEEE 754 compliant as a numerical value. They are floating point values with a significand that has variable precision (at least 106 bits (including hidden bits), at most ..more.. where the intervening bits between the two stored values are all zeros). And an exponent that has fixed precision (matching e.g. the exponent range of a Float64).

The delay in my response was unavoidable.

**Comment by JeffreySarnoff** [comment]
Resolving the need expressed by @saschatimme (https://github.com/JuliaMath/DoubleFloats.jl/issues/34) was best accomplished using the originally intended representation for `Inf`, `NaN` where the LO part is NaN.  I have gone through the code and modified everything that needed changing (afaik).  The result is now tagged and merged as v0.5.0.
I am quite open to other PRs you may see as appropriate to the project.

**Pull request closed without merging**
